name: venv-eva4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - pylint
    - autopep8
    - yapf
    - black
    - pipreqs
    - pipdeptree
    - pip-tools
    - pip-compile-multi


